#!/usr/bin/python3
"""Defines unittests for base.py."""

import unittest
import json
from models.base import Base
from models.rectangle import Rectangle
from models.square import Square


class TestBase(unittest.TestCase):
    def test_base_id_increment(self):
        b1 = Base()
        b2 = Base()
        self.assertEqual(b1.id, 1)
        self.assertEqual(b2.id, 2)

    def test_base_given_id(self):
        b = Base(5)
        self.assertEqual(b.id, 5)


class TestRectangle(unittest.TestCase):
    def test_rectangle_attributes(self):
        r = Rectangle(2, 3, 4, 5)
        self.assertEqual(r.width, 2)
        self.assertEqual(r.height, 3)
        self.assertEqual(r.x, 4)
        self.assertEqual(r.y, 5)

    def test_rectangle_area(self):
        r = Rectangle(4, 5)
        self.assertEqual(r.area(), 20)


class TestSquare(unittest.TestCase):
    def test_square_attributes(self):
        s = Square(2, 4, 5)
        self.assertEqual(s.size, 2)
        self.assertEqual(s.x, 4)
        self.assertEqual(s.y, 5)

    def test_square_area(self):
        s = Square(3)
        self.assertEqual(s.area(), 9)


if __name__ == '__main__':
    unittest.main()
